heat_template_version: 2015-10-15

description: Sample template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.tiny
      networks:
        - network: private
